### ISSUE TITLE
javac compiler fails when processor creates resource

### ISSUE THREAD

**Issue by WonderCsabo** [takari/takari-lifecycle#20]
In AndroidAnnotations, we [create some dummy resource files](https://github.com/excilys/androidannotations/blob/326fe9666df37284245c4e2706f4c042f0b396c1/AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/FileHelper.java#L54) to locate the folder. This is not causing any problems with the current build systems (Eclipse JDT, maven-compiler-plugin, Gradle). However the takari javac compiler fails with this stacktrace:
```
Caused by: java.lang.IllegalArgumentException: File does not exist or cannot be read \target\generated-sources\annotations\dummy1433691094555
        at io.takari.incrementalbuild.spi.AbstractBuildContext.newFileState(AbstractBuildContext.java:297)
        at io.takari.incrementalbuild.spi.AbstractBuildContext.commit(AbstractBuildContext.java:504)
        at io.takari.incrementalbuild.maven.internal.MavenBuildContextFinalizer.afterMojoExecutionSuccess(MavenBuildContextFinalizer.java:78)
        at org.apache.maven.execution.scope.internal.MojoExecutionScope.afterMojoExecutionSuccess(MojoExecutionScope.java:163)
        at org.apache.maven.plugin.CompoundMojoExecutionListener.afterMojoExecutionSuccess(CompoundMojoExecutionListener.java:52)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:136)
        ... 21 more
```

**Comment by ifedorenko** [comment]
Sorry, Github is eating notification emails :-( Will have a look in next few days

**Comment by WonderCsabo** [comment]
No problem. Thanks!
