### ISSUE TITLE
takari-maven-plugin compile incompatible with spring-boot-starter-log4j2

### ISSUE THREAD

**Issue by fireboy1919** [takari/takari-lifecycle#56]
Looks like maybe it's log4j's fault, but I don't know enough about this cycle to give a good guess.
Here's the produced cause:
```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-compile of goal io.takari.maven.plugins:takari-lifecycle-plugin:1.13.1:compile failed: <proc> must be one of 'none', 'only' or 'proc'. Processors found: 
   C:\Users\rusty\.m2\repository\org\apache\logging\log4j\log4j-core\2.7\log4j-core-2.7.jar [#, #      http://www.apache.org/licenses/LICENSE-2.0, # (the "License"); you may not use this file except in compliance with, # Licensed to the Apache Software Foundation (ASF) under one or more, # See the license for the specific language governing permissions and, # The ASF licenses this file to You under the Apache license, Version 2.0, # Unless required by applicable law or agreed to in writing, software, # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied., # contributor license agreements. See the NOTICE file distributed with, # distributed under the License is distributed on an "AS IS" BASIS,, # limitations under the license., # the License. You may obtain a copy of the License at, # this work for additional information regarding copyright ownership., org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
```

**Comment by ifedorenko** [comment]
You need to explicitly tell takari lifecycle what to do when annotation processors are present on compile path. If you need the processor to run, add `<proc>proc</proc>` to the plugin configuration, if you don't want the processor to run, add `<proc>none</proc>`.
